# The onboard MCU on the Ferris is an STM32F072,
# which has only 16kB of Flash and 4kB of RAM.
# A very simple / stripped build is needed.
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_STUDIO=n

# Just about cut in half the amount of quantum keys handeled,
# in order somewhat significantly reduce RAM usage
CONFIG_ZMK_BEHAVIOR_STICKY_KEY_MAX_HELD=4
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_HELD=6
CONFIG_ZMK_BEHAVIOR_HOLD_TAP_MAX_CAPTURED_EVENTS=20
